# nome identificador da aplicação
spring.application.name=flashcards

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# diz ao Hibernate para criar/atualizar as tabelas automaticamente a partir das suas classes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect